package course

/*
CREATE TABLE course
(
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    owner INT NOT NULL,
    FOREIGN KEY(owner) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE tag
(
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    course INT NOT NULL,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE learn
(
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    student INT NOT NULL,
    course INT NOT NULL,
    FOREIGN KEY(student) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE teach
(
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    teacher INT NOT NULL,
    course INT NOT NULL,
    FOREIGN KEY(teacher) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE comment
(
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    user INT NOT NULL,
    course INT NOT NULL,
    rate INT NOT NULL,
    comment TEXT NOT NULL,
    FOREIGN KEY(user) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);
*/
