package course

/*
CREATE TABLE course
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    owner INTEGER NOT NULL,
    tag TEXT NOT NULL,
    FOREIGN KEY(owner) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE relation
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    course INTEGER NOT NULL,
    user INTEGER NOT NULL,
    relation INTEGER NOT NULL,
    FOREIGN KEY(user) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE comment
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    course INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    comment TEXT NOT NULL,
    FOREIGN KEY(user) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);
*/
