package forum

/*
CREATE TABLE forum
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    course INTEGER NOT NULL,
    video INTEGER NOT NULL,
    content TEXT NOT NULL,
    time INTEGER NOT NULL,
    FOREIGN KEY(user) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(video) REFERENCES video(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE reply
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    forum INTEGER NOT NULL,
    content TEXT NOT NULL,
    time INTEGER NOT NULL,
    FOREIGN KEY(user) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(forum) REFERENCES forum(id) ON UPDATE CASCADE ON DELETE CASCADE
);
*/

type Forum struct {
}

type Reply struct {
}
